version: "3.7"
services:
  traefik:
    image: "traefik:v2.8"
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.mends.eu`)
      - traefik.http.routers.traefik-secure.service=api@internal
      - traefik.http.routers.traefik-secure.tls.certresolver=myresolver
    networks:
      - traefik
  portainer:
    image: portainer/portainer-ee:2.15.1
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.frontend.rule=Host(`portainer.mends.eu`)
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.services.frontend.loadbalancer.server.port=9000
        - traefik.http.routers.frontend.service=frontend
        - traefik.http.routers.frontend.tls.certresolver=myresolver
      # Edge
      - traefik.http.routers.edge.rule=Host(`edge.mends.eu`)
      - traefik.http.routers.edge.entrypoints=websecure
      - traefik.http.services.edge.loadbalancer.server.port=8000
      - traefik.http.routers.edge.service=edge
      - traefik.http.routers.edge.tls.certresolver=myresolver
    networks:
      - traefik
volumes:
  traefik_letsencrypt:
    name: traefik_letsencrypt
  portainer_data:
    name: portainer_data
networks:
  traefik:
    name: traefik
